import type { Client, Product, Order, Expense, LogEntry } from '../types';

export const initialClients: Client[] = [
  { id: 'alb', displayId: 1, name: 'Alain Basque', phone: '(438) 342-5879', address: 'Montreal', notes: 'Juin 2025 grindr blacklisted', orders: 0, totalSpent: 0 },
  { id: 'alx', displayId: 2, name: 'Alex sauna camping', phone: '(613) 861-4855', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'coup', displayId: 3, name: 'Alex', phone: '(514) 424-3810', address: '4892 papineau', notes: 'Couple Plateau beaucoup md+onz we+vi', orders: 0, totalSpent: 0 },
  { id: 'amjd', displayId: 4, name: 'Amjad', phone: '(438) 929-0408', address: 'Montreal', notes: 'Blacklisted rencontrer sauna janvier 2025', orders: 0, totalSpent: 0 },
  { id: 'benb', displayId: 5, name: 'Ben Bringer', phone: '(514) 497-6184', address: '1435 rue cuvillier, Montreal', notes: 'Livreur mickey mike voisin', orders: 0, totalSpent: 0 },
  { id: 'amar', displayId: 6, name: 'Amar daddy grindr', phone: '(438) 820-5572', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'ashl', displayId: 7, name: 'Ashley Gauthier', phone: '(514) 972-6700', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'bran', displayId: 8, name: 'Brandon Cutie Rs', phone: '(514) 805-7523', address: 'Montreal', notes: 'blacklisted dette200$ statut inactif', orders: 0, totalSpent: 0 },
  { id: 'brun', displayId: 9, name: 'Bruno', phone: '(514) 589-2990', address: 'Montreal', notes: 'blacklisted fatiguant', orders: 0, totalSpent: 0 },
  { id: 'chet', displayId: 10, name: 'Charles-Etienne', phone: '(438) 365-8319', address: 'Montreal', notes: 'Dette 20$ vi statut inactif', orders: 0, totalSpent: 0 },
  { id: 'cmac', displayId: 11, name: 'Christopher Maclean', phone: '', address: 'Montreal', notes: 'Ami de rassim statut dette 50$ inactif', orders: 0, totalSpent: 0 },
  { id: 'cia', displayId: 12, name: 'Ciavia client', phone: '(450) 898-3928', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'claud', displayId: 13, name: 'Claude Noel', phone: '(514) 835-2971', address: 'Montreal', notes: 'Camping achat en gros', orders: 0, totalSpent: 0 },
  { id: '500', displayId: 14, name: 'Client 500$coke', phone: '(438) 399-5826', address: '6950 boul des roserais', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dall', displayId: 15, name: 'Client Dallas', phone: '(214) 985-8245', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dir', displayId: 16, name: 'Kevin dirty dog', phone: '(514) 466-8890', address: '1000 de la commune apt418', notes: 'Bulk buyer', orders: 0, totalSpent: 0 },
  { id: 'sous', displayId: 17, name: 'Client Soumis', phone: '(438) 884-3566', address: 'Montreal', notes: 'Supplement arrêter condo juin 2025 statut inactif', orders: 0, totalSpent: 0 },
  { id: 'danx', displayId: 18, name: 'Daniel Excoloc', phone: '(438) 929-9712', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dom', displayId: 19, name: 'dom jockey', phone: '(438) 700-3519', address: '', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dani', displayId: 20, name: 'Dani daddy sauna', phone: '(514) 246-2672', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dim', displayId: 21, name: 'Dimitry voisin', phone: '', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dfbi', displayId: 22, name: 'David FBI', phone: '(438) 834-4233', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'don', displayId: 23, name: 'Donald', phone: '(514) 265-6713', address: '2292 rue cuvillier', notes: '', orders: 0, totalSpent: 0 },
  { id: 'eddi', displayId: 24, name: 'Eddie red bull', phone: '(438) 350-4478', address: 'Montreal', notes: 'Sp et 1/2 blanc Easygay', orders: 0, totalSpent: 0 },
  { id: 'edmu', displayId: 25, name: 'Edmundo', phone: '(514) 546-2017', address: 'Montreal', notes: 'Ex de Philippe Rivard statut inactif', orders: 0, totalSpent: 0 },
  { id: 'eric', displayId: 26, name: 'Eric Benard leather domtop', phone: '(514) 581-2465', address: 'Montreal', notes: 'leather domtop', orders: 0, totalSpent: 0 },
  { id: 'eric2', displayId: 27, name: 'Eric Deveau', phone: '(438) 370-3310', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'feli', displayId: 28, name: 'Felipe', phone: '(438) 518-3829', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'ffbd', displayId: 29, name: 'Ffbeaudry', phone: '(514) 727-2437', address: 'Village, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'fraa', displayId: 30, name: 'Francis Auger', phone: '(438) 887-8512', address: '3544 Rue Ontario E Montréal QC H1W 1R5 Canada', notes: 'Cousin pingouin', orders: 0, totalSpent: 0 },
  { id: 'fran', displayId: 31, name: 'Francois Palmiee', phone: '(514) 349-7916', address: 'Camping', notes: 'Camping achat en gros', orders: 0, totalSpent: 0 },
  { id: 'fnk', displayId: 32, name: 'FRANK', phone: '', address: 'Montreal', notes: 'Voleur menteur blacklisted', orders: 0, totalSpent: 0 },
  { id: 'dee', displayId: 33, name: 'Frankee Dee', phone: '(263) 382-9132', address: 'Montreal', notes: '2grT 60$', orders: 0, totalSpent: 0 },
  { id: 'gabt', displayId: 34, name: 'Gab Thibeault', phone: '(438) 408-7559', address: 'Montreal', notes: 'Chum a Camille', orders: 0, totalSpent: 0 },
  { id: 'gser', displayId: 35, name: 'Gabriel Serrano', phone: '(514) 299-8980', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'ger', displayId: 36, name: 'Gerome', phone: '(514) 506-7593', address: 'Montreal', notes: 'Francais', orders: 0, totalSpent: 0 },
  { id: 'ghis', displayId: 37, name: 'Ghislain', phone: '(514) 452-1819', address: '2211 l\'esperance ,apt #202 , Montreal', notes: 'Ghislain l', orders: 0, totalSpent: 0 },
  { id: 'gilb', displayId: 38, name: 'Gil Bert gizmo', phone: '(438) 227-1152', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'greg', displayId: 39, name: 'Greg', phone: '(514) 971-7191', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'guy', displayId: 40, name: 'Guy', phone: '(514) 213-0731', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'nurs', displayId: 41, name: 'Guy Nurse', phone: '(438) 834-0605', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'love', displayId: 42, name: 'Hachim lover Grindr', phone: '(514) 349-0807', address: '2Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'hugo', displayId: 43, name: 'Hugo Michael', phone: '(438) 765-4461', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'ianf', displayId: 44, name: 'Ian francoqueb', phone: '(438) 523-2992', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jakg', displayId: 45, name: 'JACQUES SAUNA KILO', phone: '(579) 369-1113', address: 'Montreal', notes: 'Vendu kilo sauna daddy', orders: 0, totalSpent: 0 },
  { id: 'jaso', displayId: 46, name: 'Jason', phone: '(514) 463-2841', address: 'Montreal', notes: 'E ci', orders: 0, totalSpent: 0 },
  { id: 'latn', displayId: 47, name: 'Jason latino', phone: '(514) 430-4295', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jasn', displayId: 48, name: 'Jason Niles', phone: '(250) 858-4574', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jay', displayId: 49, name: 'Jay Frontenac', phone: '(514) 928-7638', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jl', displayId: 50, name: 'Jean luc', phone: '(438) 495-8221', address: 'Montreal', notes: 'Easygaychat', orders: 0, totalSpent: 0 },
  { id: 'jraf', displayId: 51, name: 'Jean-Raphaël Aspirot', phone: '(418) 563-5298', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jesy', displayId: 52, name: 'Jesse Coupons', phone: '(438) 834-3548', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jim', displayId: 53, name: 'Jimmy-me', phone: '(450) 944-7089', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'joe', displayId: 54, name: 'Joe', phone: '(438) 528-5900', address: 'Montreal', notes: 'Ami de Martin*', orders: 0, totalSpent: 0 },
  { id: 'rex', displayId: 55, name: 'John REX T-Rex', phone: '(438) 888-0522', address: '3544 Rue Ontario E Montréal QC H1W 1R5 Canada', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jmac', displayId: 56, name: 'John Macadams', phone: '(514) 604-2009', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jorg', displayId: 57, name: 'Jorge grindr', phone: '(514) 291-7189', address: 'Montreal', notes: 'Referer kevin Jorge top latino beef', orders: 0, totalSpent: 0 },
  { id: 'josh', displayId: 58, name: 'Joshua My Jew', phone: '(514) 224-5531', address: '4157 rue Mentana, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'juan', displayId: 59, name: 'Juan Feler', phone: '(438) 459-4536', address: '4865 Rue Partenais, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'krm', displayId: 60, name: 'Karim', phone: '(514) 473-2107', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'kiral', displayId: 61, name: 'Kiral', phone: '(514) 561-0432', address: 'Montreal Verdun', notes: '', orders: 0, totalSpent: 0 },
  { id: 'kevd', displayId: 62, name: 'Kevin Duhaime', phone: '(438) 829-9791', address: '2479 Rue Logan, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'kyle', displayId: 63, name: 'Kyle', phone: '(438) 529-5949', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'lati', displayId: 64, name: 'Latino ami jraf', phone: '(514) 836-6552', address: 'Montreal', notes: 'Ami jraf latino piercing', orders: 0, totalSpent: 0 },
  { id: 'lfaf', displayId: 65, name: 'Luis fafard', phone: '(438) 406-5847', address: '2893 rouen , Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'lucg', displayId: 66, name: 'Luc Girard', phone: '(438) 399-5826', address: '6950 boul. Des Roserais, Anjou', notes: '', orders: 0, totalSpent: 0 },
  { id: 'luca', displayId: 67, name: 'Lucas linette', phone: '(438) 435-2667', address: 'Montreal', notes: 'Muscle hotstud referer de kevin', orders: 0, totalSpent: 0 },
  { id: 'mara', displayId: 68, name: 'Marc Asselin', phone: '(514) 464-0842', address: '3885 avenue colons, Brossard', notes: 'Rive sud pozguy', orders: 0, totalSpent: 0 },
  { id: 'marl', displayId: 69, name: 'Marc Lauzon', phone: '(438) 882-5593', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'marcx', displayId: 70, name: 'Marco', phone: '(514) 996-8860', address: 'Rue lasalle , Montreal', notes: 'Blacklisted dois 150$ rue Lasalle', orders: 0, totalSpent: 0 },
  { id: 'maco', displayId: 71, name: 'Marco Priape', phone: '(514) 616-2328', address: 'Rue Viau, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'mat', displayId: 72, name: 'Mathieu Fillion', phone: '(514) 895-9375', address: '', notes: '', orders: 0, totalSpent: 0 },
  { id: 'mare', displayId: 73, name: 'Marek', phone: '(416) 906-6773', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'mart', displayId: 74, name: 'Martin *', phone: '(438) 988-1587', address: '5322 Partenais , Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'marv', displayId: 75, name: 'Marvel junior', phone: '(514) 552-6937', address: 'Davidson /st-catherine', notes: '', orders: 0, totalSpent: 0 },
  { id: 'maxl', displayId: 76, name: 'Maxime Lachance', phone: '(514) 574-7383', address: '1883 Rene levesques', notes: '', orders: 0, totalSpent: 0 },
  { id: 'medo', displayId: 77, name: 'Meedo Mohamed', phone: '(514) 999-5747', address: 'Pyramides olympiques', notes: 'Blacklisted', orders: 0, totalSpent: 0 },
  { id: 'micx', displayId: 78, name: 'Michael Belec Coloc', phone: '(514) 233-4206', address: 'Montreal', notes: 'Doit 1100$ loyer plus drogues', orders: 0, totalSpent: 0 },
  { id: 'momo', displayId: 79, name: 'Momo', phone: '(438) 921-9195', address: 'Montreal', notes: 'Ami de meedo blacklisted', orders: 0, totalSpent: 0 },
  { id: 'nicb', displayId: 80, name: 'Nicholas Bougie', phone: '(438) 879-0230', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'nico', displayId: 81, name: 'Nicolas', phone: '(514) 779-8357', address: 'Montreal', notes: 'Ami Donald', orders: 0, totalSpent: 0 },
  { id: 'nkp', displayId: 82, name: 'Francis nkp', phone: '(514) 437-0401', address: 'Montreal', notes: 'Indetect top électronique', orders: 0, totalSpent: 0 },
  { id: 'omar', displayId: 83, name: 'Omar Badawi', phone: '(438) 365-7222', address: 'Montreal', notes: 'Rue sussex', orders: 0, totalSpent: 0 },
  { id: 'pat', displayId: 84, name: 'Pat Voleur', phone: '(514) 249-6705', address: 'Montreal', notes: 'Voleur menteur vole 2onz co 2000$', orders: 0, totalSpent: 0 },
  { id: 'pats', displayId: 85, name: 'Patric surprenant hotel', phone: '(418) 313-4063', address: 'Montreal', notes: 'Patric hotel rencontrer meedo', orders: 0, totalSpent: 0 },
  { id: 'patv', displayId: 86, name: 'Patrick de Varennes', phone: '(514) 702-4558', address: 'Montreal', notes: 'Grindr hookup decevant', orders: 0, totalSpent: 0 },
  { id: 'phil', displayId: 87, name: 'Philippe Rivard', phone: '(873) 455-9117', address: '3544 Rue Ontario E Montréal QC H1W 1R5 Canada', notes: 'Room mate = 1 gr 30', orders: 0, totalSpent: 0 },
  { id: 'raph', displayId: 88, name: 'Raphael', phone: '(438) 812-4976', address: 'Montreal', notes: 'Lover', orders: 0, totalSpent: 0 },
  { id: 'rass', displayId: 89, name: 'Rassim', phone: '(514) 882-9480', address: 'Montreal', notes: 'Fucked up kinda blacklist', orders: 0, totalSpent: 0 },
  { id: 'remi', displayId: 90, name: 'Remi racine', phone: '(514) 473-7399', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'rick', displayId: 91, name: 'Richard Bolduc', phone: '(579) 373-2220', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'robb', displayId: 92, name: 'Roberto', phone: '(438) 470-0929', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'said', displayId: 93, name: 'Said', phone: '(514) 244-0114', address: 'Montreal', notes: 'Hung top baise pu bon prix quand meme', orders: 0, totalSpent: 0 },
  { id: 'samd', displayId: 94, name: 'Sam Dupras', phone: '(289) 984-1337', address: '3544 Rue Ontario E', notes: '', orders: 0, totalSpent: 0 },
  { id: 'samb', displayId: 95, name: 'Samuel Bergeron', phone: '(514) 207-8533', address: 'Montreal', notes: 'Fatiguant', orders: 0, totalSpent: 0 },
  { id: 'sebf', displayId: 96, name: 'Sébastien Fortin', phone: '(438) 799-4420', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'sean', displayId: 97, name: 'Shean black', phone: '(514) 922-8819', address: 'Montreal', notes: 'Doit 100$', orders: 0, totalSpent: 0 },
  { id: 'shuj', displayId: 98, name: 'Shuja', phone: '(438) 465-7293', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'simk', displayId: 99, name: 'Simon Kingston', phone: '(514) 791-1785', address: 'Montreal', notes: 'Doit 200$', orders: 0, totalSpent: 0 },
  { id: 'step', displayId: 100, name: 'Stephan rue Lasalle', phone: '(514) 778-3172', address: 'Rue lasalle , Montreal', notes: 'Peintre', orders: 0, totalSpent: 0 },
  { id: 'tesd', displayId: 101, name: 'Tesdy mtl Grindr', phone: '(514) 608-5882', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'tier', displayId: 102, name: 'Thierry Etienne Olga', phone: '(438) 765-9326', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dimm', displayId: 103, name: 'Voisin Dimitry', phone: '(438) 491-9625', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'wale', displayId: 104, name: 'Waleed', phone: '(514) 213-6957', address: 'Montreal', notes: 'App builder', orders: 0, totalSpent: 0 },
  { id: 'walh', displayId: 105, name: 'waleed Hakim', phone: '(613) 255-1026', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'xx', displayId: 106, name: 'XX', phone: '(514) 777-7777', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'xav', displayId: 107, name: 'Xavier POS', phone: '(514) 444-4405', address: 'Montreal', notes: 'Poz admin slmMontreal', orders: 0, totalSpent: 0 },
  { id: 'karb', displayId: 108, name: 'Karim reflouis', phone: '(438) 540-2422', address: 'Montreal', notes: 'Référé luis Fafard bank account fake id', orders: 0, totalSpent: 0 },
  { id: 'chei', displayId: 109, name: 'Cheick', phone: '(514) 709-2607', address: 'Montreal', notes: 'Black dom Préfontaine group', orders: 0, totalSpent: 0 },
  { id: 'tuper', displayId: 110, name: 'tuper', phone: '(514) 756-0831', address: '1821 Tupper street Montreal', notes: '10 via noir easygaychat', orders: 0, totalSpent: 0 }
];

export const initialProducts: Product[] = [
  // Main products with multiple weight options
  { id: 'ti', name: 'Ti', type: 'g', stock: 0, price: 30, referenceQuantity: '1g/2g/3.5g/7g/14g/28g/100g/500g/1000g', suggestedPrice: '30/60/130/200/300/450/1800/4900/8000', cost: '6/12/21/42/84/168/600/3000/6000' },
  { id: 'we', name: 'We', type: 'g', stock: 0, price: 5, referenceQuantity: '0.5g/3.5g/28g', suggestedPrice: '5/20/90', cost: '3/11/50' },
  { id: 'ket', name: 'Ket', type: 'g', stock: 0, price: 40, referenceQuantity: '0.33g/1g/28g', suggestedPrice: '40/90/750', cost: '7/20/550' },
  { id: 'coco', name: 'Coco', type: 'g', stock: 0, price: 50, referenceQuantity: '0.5g/1g/3.5g/28g', suggestedPrice: '50/90/280/1200', cost: '25/50/175/950' },

  // GH products
  { id: 'gh', name: 'GH', type: 'ml', stock: 0, price: 10, referenceQuantity: '5ml/20ml/60ml/100ml/1000ml', suggestedPrice: '10/40/100/180/1400', cost: '1/14/40/70/700' },

  // Vi products
  { id: 'viblue', name: 'Vi Blue', type: 'unit', stock: 0, price: 6, referenceQuantity: '100mg', suggestedPrice: '6', cost: '2' },
  { id: 'vipurple', name: 'Vi Purple', type: 'unit', stock: 0, price: 8, referenceQuantity: '100mg', suggestedPrice: '8', cost: '2' },
  { id: 'vired', name: 'Vi Red', type: 'unit', stock: 0, price: 10, referenceQuantity: '150mg', suggestedPrice: '10', cost: '2' },
  { id: 'viblack', name: 'Vi Black', type: 'unit', stock: 0, price: 10, referenceQuantity: '200mg', suggestedPrice: '10', cost: '3' },
  { id: 'vilevi', name: 'Vi Levi', type: 'unit', stock: 0, price: 12, referenceQuantity: '60mg', suggestedPrice: '12', cost: '3' },
  { id: 'vikamjelly', name: 'Vi Kam Jelly', type: 'unit', stock: 0, price: 10, referenceQuantity: '100mg', suggestedPrice: '10', cost: '3' },

  // Ci products
  { id: 'ci20mg', name: 'Ci 20mg', type: 'unit', stock: 0, price: 8, referenceQuantity: '20mg', suggestedPrice: '8', cost: '3' },
  { id: 'ci60mg', name: 'Ci 60mg', type: 'unit', stock: 0, price: 10, referenceQuantity: '60mg', suggestedPrice: '10', cost: '3' },
  { id: 'ci80mg', name: 'Ci 80mg', type: 'unit', stock: 0, price: 12, referenceQuantity: '80mg', suggestedPrice: '12', cost: '3' },

  // Other products
  { id: 'sp', name: 'Sp', type: 'unit', stock: 0, price: 3, referenceQuantity: '1 unit', suggestedPrice: '3', cost: '1' },
  { id: 'e', name: 'E', type: 'unit', stock: 0, price: 8, referenceQuantity: '1 unit', suggestedPrice: '8', cost: '2' },
  { id: 'md', name: 'Md', type: 'unit', stock: 0, price: 8, referenceQuantity: '1 unit', suggestedPrice: '8', cost: '4' },
  { id: 'md1g', name: 'Md 1g', type: 'g', stock: 0, price: 70, referenceQuantity: '1g', suggestedPrice: '70', cost: '20' },

  // Ha
  { id: 'ha', name: 'Ha', type: 'g', stock: 0, price: 10, referenceQuantity: '1g', suggestedPrice: '10', cost: '3' },

  // Mu
  { id: 'mu', name: 'Mu', type: 'g', stock: 0, price: 25, referenceQuantity: '3.5g/28g', suggestedPrice: '25/150', cost: '17/69' },

  // Pop
  { id: 'pop', name: 'Pop', type: 'unit', stock: 0, price: 55, referenceQuantity: '30ml/60ml', suggestedPrice: '55/75', cost: '25/35' },

  // Accessories
  { id: 'pi', name: 'Pi', type: 'unit', stock: 0, price: 5, referenceQuantity: '1 unit', suggestedPrice: '5', cost: '2' },
  { id: 'li', name: 'Li', type: 'unit', stock: 0, price: 10, referenceQuantity: '1 unit', suggestedPrice: '10', cost: '4' },
  { id: 'bo', name: 'Bo', type: 'unit', stock: 0, price: 30, referenceQuantity: '1 unit', suggestedPrice: '30', cost: '15' }
];

export const initialOrders: Order[] = [];
export const initialExpenses: Expense[] = [];
export const initialLogs: LogEntry[] = [];