#!/bin/bash

echo "🔧 Manual Deployment Script"
echo "=========================="
echo ""
echo "The token authentication isn't working through the command line."
echo "Here are alternative methods:"
echo ""
echo "METHOD 1: GitHub Desktop"
echo "1. Download GitHub Desktop: https://desktop.github.com/"
echo "2. Sign in as moarbetsy"
echo "3. Add this local repository"
echo "4. Push to origin/main"
echo ""
echo "METHOD 2: VS Code"
echo "1. Open this folder in VS Code"
echo "2. Install GitHub extension"
echo "3. Sign in as moarbetsy"
echo "4. Use Source Control to push"
echo ""
echo "METHOD 3: New Token"
echo "1. Go to https://github.com/settings/tokens"
echo "2. Delete the current token"
echo "3. Create a new token with 'repo' scope"
echo "4. Try: git remote set-url origin https://moarbetsy:NEW_TOKEN@github.com/moarbetsy/LiquidGlass.git"
echo "5. Then: git push -u origin main"
echo ""
echo "METHOD 4: Upload ZIP"
echo "1. Create ZIP of all files (except .git folder)"
echo "2. Go to https://github.com/moarbetsy/LiquidGlass"
echo "3. Upload files manually"
echo ""
echo "Once uploaded, enable GitHub Pages:"
echo "- Go to Settings → Pages"
echo "- Set Source to 'GitHub Actions'"
echo "- Your app will be live at: https://moarbetsy.github.io/LiquidGlass/"
echo ""
echo "Default login: admin / admin"