import type { Client, Product, Order, Expense, LogEntry } from '../types';

export const initialClients: Client[] = [
  { id: 'Coup', displayId: 1, name: 'Alex', phone: '(514) 424-3810', address: '4892 Papineau', notes: 'Couple Plateau', orders: 0, totalSpent: 0 },
  { id: 'amar', displayId: 2, name: 'Amar', phone: '(438) 820-5572', address: 'Montreal', notes: 'daddy grindr', orders: 0, totalSpent: 0 },
  { id: 'ashl', displayId: 3, name: 'Ashley Gauthier', phone: '(514) 972-6700', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'ciav', displayId: 4, name: 'Ciavia client', phone: '(450) 898-3928', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'claud', displayId: 5, name: 'Claude Noel', phone: '(514) 835-2971', address: 'Montreal', notes: 'Camping achat en gros', orders: 0, totalSpent: 0 },
  { id: '500', displayId: 6, name: 'Client 500$coke', phone: '(438) 399-5826', address: '6950 boul des roserais', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dall', displayId: 7, name: 'Client Dallas', phone: '(214) 985-8245', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'danx', displayId: 8, name: 'Daniel Excoloc', phone: '(438) 929-9712', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dani', displayId: 9, name: 'Dani daddy sauna', phone: '(514) 246-2672', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dfbi', displayId: 10, name: 'David FBI', phone: '(438) 834-4233', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'don', displayId: 11, name: 'Donald Browne', phone: '(514) 265-6713', address: '2292 rue cuviiller', notes: '', orders: 0, totalSpent: 0 },
  { id: 'eddi', displayId: 12, name: 'Eddie red bull', phone: '(438) 350-4478', address: 'Montreal', notes: 'Easygay', orders: 0, totalSpent: 0 },
  { id: 'Eric', displayId: 13, name: 'Eric Benard', phone: '(514) 581-2465', address: 'Montreal', notes: 'Leather domtop', orders: 0, totalSpent: 0 },
  { id: 'feli', displayId: 14, name: 'Felipe', phone: '(438) 518-3829', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'fraa', displayId: 15, name: 'Francis Auger', phone: '(438) 887-8512', address: '3544 Rue Ontario E', notes: 'Cousin pingouin', orders: 0, totalSpent: 0 },
  { id: 'fran', displayId: 16, name: 'Francois Palmiee', phone: '(514) 349-7916', address: 'Camping', notes: 'Camping achat en gros', orders: 0, totalSpent: 0 },
  { id: 'dee', displayId: 17, name: 'Frankee Dee', phone: '(263) 382-9132', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'gabt', displayId: 18, name: 'Gab Thibeault', phone: '(438) 408-7559', address: 'Montreal', notes: 'Chum à Camille', orders: 0, totalSpent: 0 },
  { id: 'ger', displayId: 19, name: 'Gerome', phone: '(514) 506-7593', address: 'Montreal', notes: 'Francais', orders: 0, totalSpent: 0 },
  { id: 'ghis', displayId: 20, name: 'Ghislain', phone: '(514) 452-1819', address: '2211 l\'esperance, apt #202, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'gilb', displayId: 21, name: 'Gil Bert gizmo', phone: '(438) 227-1152', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'greg', displayId: 22, name: 'Greg', phone: '(514) 971-7191', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'guy', displayId: 23, name: 'Guy', phone: '(514) 213-0731', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'nurs', displayId: 24, name: 'Guy Nurse', phone: '(438) 834-0605', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'love', displayId: 25, name: 'Hachim', phone: '', address: 'Montreal', notes: 'lover Grindr', orders: 0, totalSpent: 0 },
  { id: 'hugo', displayId: 26, name: 'Hugo Michael', phone: '(438) 765-4461', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'ianf', displayId: 27, name: 'lan', phone: '(438) 523-2992', address: 'Montreal', notes: 'Francoqueb', orders: 0, totalSpent: 0 },
  { id: 'jakg', displayId: 28, name: 'Jacques', phone: '(579) 369-1113', address: 'Montreal', notes: 'Sauna daddy', orders: 0, totalSpent: 0 },
  { id: 'jaso', displayId: 29, name: 'Jason', phone: '(514) 463-2841', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Latn', displayId: 30, name: 'Jason latino', phone: '(514) 430-4295', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jasn', displayId: 31, name: 'Jason Niles', phone: '(250) 858-4574', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jraf', displayId: 32, name: 'Jean-Raphaël Aspirot', phone: '(418) 563-5298', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Jesy', displayId: 33, name: 'Jesse Coupons', phone: '(438) 834-3548', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jim', displayId: 34, name: 'Jimmy-me', phone: '(450) 944-7089', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Joe', displayId: 35, name: 'Joe', phone: '(438) 528-5900', address: 'Montreal', notes: 'Ami de Martin*', orders: 0, totalSpent: 0 },
  { id: 'Rex', displayId: 36, name: 'John REX T-Rex', phone: '(438) 888-0522', address: '3544 Rue Ontario E', notes: '', orders: 0, totalSpent: 0 },
  { id: 'jorg', displayId: 37, name: 'Jorge grindr', phone: '(514) 291-7189', address: 'Montreal', notes: 'Referer Kevin Jorge top latino beef', orders: 0, totalSpent: 0 },
  { id: 'josh', displayId: 38, name: 'Joshua My Jew', phone: '(514) 224-5531', address: '4157 rue Mentana, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'juan', displayId: 39, name: 'Juan Feler', phone: '(438) 459-4536', address: '4865 Rue Partenais, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'krm', displayId: 40, name: 'Karim', phone: '(514) 473-2107', address: 'Montreal', notes: 'Domtop arabe', orders: 0, totalSpent: 0 },
  { id: 'Kar', displayId: 41, name: 'Karim coolegue', phone: '(438) 540-2422', address: 'Montreal', notes: 'The best of all', orders: 0, totalSpent: 0 },
  { id: 'chik', displayId: 42, name: 'Kevin chicklette', phone: '', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Kir', displayId: 43, name: 'Kiral', phone: '(514) 561-0432', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'kyle', displayId: 44, name: 'Kyle', phone: '(438) 529-5949', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'lati', displayId: 45, name: 'Latino ami jraf', phone: '(514) 836-6552', address: 'Montreal', notes: 'Ami jraf latino piercing', orders: 0, totalSpent: 0 },
  { id: 'lfaf', displayId: 46, name: 'Luis fafard', phone: '(438) 406-5847', address: '2893 rouen, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Lucg', displayId: 47, name: 'Luc Girard', phone: '(438) 399-5826', address: '6950 boul. Des Roserais, Anjou', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Luca', displayId: 48, name: 'Lucas linette', phone: '(438) 435-2667', address: 'Montreal', notes: 'Muscle hotstud referer de kevin', orders: 0, totalSpent: 0 },
  { id: 'Mara', displayId: 49, name: 'Marc Asselin', phone: '(514) 464-0842', address: '3885 avenue colons, Brossard', notes: 'Rive sud pozguy', orders: 0, totalSpent: 0 },
  { id: 'marl', displayId: 50, name: 'Marc Lauzon', phone: '(438) 882-5593', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'marcx', displayId: 51, name: 'Marco', phone: '(514) 996-8860', address: 'Rue lasalle, Montreal', notes: 'Blacklisted dois 150$ rue Lasalle', orders: 0, totalSpent: 0 },
  { id: 'maco', displayId: 52, name: 'Marco Priape', phone: '(514) 616-2328', address: 'Rue Viau, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'mare', displayId: 53, name: 'Marek', phone: '(416) 906-6773', address: 'Montreal', notes: 'Ref. Meedoe', orders: 0, totalSpent: 0 },
  { id: 'Mart', displayId: 54, name: 'Martin *', phone: '(438) 988-1587', address: '5322 Partenais, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'marv', displayId: 55, name: 'Marvel junior', phone: '(514) 552-6937', address: 'Davidson /st-catherine', notes: '', orders: 0, totalSpent: 0 },
  { id: 'maxl', displayId: 56, name: 'Maxime Lachance', phone: '(514) 574-7383', address: '1883 Rene levesques', notes: '', orders: 0, totalSpent: 0 },
  { id: 'micx', displayId: 57, name: 'Michael Belec', phone: '(514) 233-4206', address: 'Montreal', notes: 'Coloc, Doit 1100$ loyer plus drogues', orders: 0, totalSpent: 0 },
  { id: 'nico', displayId: 58, name: 'Nicolas', phone: '(514) 779-8357', address: 'Montreal', notes: 'Ami Donald', orders: 0, totalSpent: 0 },
  { id: 'Nkp', displayId: 59, name: 'nkp', phone: '(514) 437-0401', address: 'Montreal', notes: 'Indetect top électronique', orders: 0, totalSpent: 0 },
  { id: 'omar', displayId: 60, name: 'Omar Badawi', phone: '(438) 365-7222', address: 'Montreal', notes: 'Rue sussex', orders: 0, totalSpent: 0 },
  { id: 'pat', displayId: 61, name: 'Pat Voleur', phone: '(514) 249-6705', address: 'Montreal', notes: 'Voleur menteur vole 2onz coke 2000$', orders: 0, totalSpent: 0 },
  { id: 'pats', displayId: 62, name: 'Patric Surprenant', phone: '(418) 313-4063', address: 'Montreal', notes: 'Patric hotel rencontrer meedo', orders: 0, totalSpent: 0 },
  { id: 'patv', displayId: 63, name: 'Patrick de Varennes', phone: '(514) 702-4558', address: 'Montreal', notes: 'Grindr hookup decevant', orders: 0, totalSpent: 0 },
  { id: 'phil', displayId: 64, name: 'Philippe Rivard', phone: '(873) 455-9117', address: '3544 Rue Ontario E Montréal', notes: 'Room mate = 1 gr 30', orders: 0, totalSpent: 0 },
  { id: 'raph', displayId: 65, name: 'Raphael (Jimmy Andres)', phone: '(438) 812-4976', address: 'Montreal', notes: 'Lover', orders: 0, totalSpent: 0 },
  { id: 'rass', displayId: 66, name: 'Rassim', phone: '(514) 882-9480', address: 'Montreal', notes: 'Fucked up kinda blacklist', orders: 0, totalSpent: 0 },
  { id: 'remi', displayId: 67, name: 'Remi racine', phone: '(514) 473-7399', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'rick', displayId: 68, name: 'Richard Bolduc', phone: '(579) 373-2220', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'robb', displayId: 69, name: 'Roberto', phone: '(416) 575-2970', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Said', displayId: 70, name: 'Said', phone: '(514) 244-0114', address: 'Montreal', notes: 'Hung top baise pu bon prix quand meme', orders: 0, totalSpent: 0 },
  { id: 'samd', displayId: 71, name: 'Sam Dupras', phone: '(289) 984-1337', address: '3544 Rue Ontario E', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Samb', displayId: 72, name: 'Samuel Bergeron', phone: '(514) 207-8533', address: 'Montreal', notes: 'Fatiguant', orders: 0, totalSpent: 0 },
  { id: 'sebf', displayId: 73, name: 'Sébastien Fortin', phone: '(438) 799-4420', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'shuj', displayId: 74, name: 'Shuja', phone: '(438) 465-7293', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Step', displayId: 75, name: 'Stephan rue Lasalle', phone: '(514) 778-3172', address: 'Rue lasalle, Montreal', notes: 'Peintre', orders: 0, totalSpent: 0 },
  { id: 'tesd', displayId: 76, name: 'Tesdy mtl Grindr', phone: '(514) 608-5882', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'tier', displayId: 77, name: 'Thierry Etienne Olga', phone: '(438) 765-9326', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'dimm', displayId: 78, name: 'Voisin Dimitry', phone: '(438) 491-9625', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'wale', displayId: 79, name: 'Waleed', phone: '(514) 213-6957', address: 'Montreal', notes: 'App builder', orders: 0, totalSpent: 0 },
  { id: 'walh', displayId: 80, name: 'waleed Hakim', phone: '(613) 255-1026', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'X', displayId: 81, name: 'X', phone: '(514) 777-7777', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'xav', displayId: 82, name: 'Xavier POS', phone: '(514) 444-4405', address: 'Montreal', notes: 'Poz admin slm', orders: 0, totalSpent: 0 },
  { id: 'chei', displayId: 83, name: 'Cheick', phone: '(514) 709-2607', address: 'Montreal', notes: 'Black dom Préfontaine group', orders: 0, totalSpent: 0 },
  { id: 'tuper', displayId: 84, name: 'Josh', phone: '(514) 756-0831', address: '1821 Tupper street Montreal', notes: '10 via noir easygaychat Jewish', orders: 0, totalSpent: 0 },
  { id: 'alb', displayId: 85, name: 'Alain Basque', phone: '(438) 342-5879', address: 'Montreal', notes: 'Juin 2025 grindr blacklisted', orders: 0, totalSpent: 0 },
  { id: 'amjd', displayId: 86, name: 'Amjad', phone: '(438) 929-0408', address: 'Montreal', notes: 'Blacklisted rencontrer sauna janvier 2025', orders: 0, totalSpent: 0 },
  { id: 'Bran', displayId: 87, name: 'Brandon Cutie Rs', phone: '(514) 805-7523', address: 'Montreal', notes: 'blacklisted dette200$ statut inactif', orders: 0, totalSpent: 0 },
  { id: 'brun', displayId: 88, name: 'Bruno', phone: '(514) 589-2990', address: 'Montreal', notes: 'blacklisted fatiguant', orders: 0, totalSpent: 0 },
  { id: 'chet', displayId: 89, name: 'Charles-Etienne', phone: '(438) 365-8319', address: 'Montreal', notes: 'Dette 20$ viagra statut inactif', orders: 0, totalSpent: 0 },
  { id: 'cmac', displayId: 90, name: 'Christopher Maclean', phone: '', address: 'Montreal', notes: 'Ami de rassim statut dette 50$ inactif', orders: 0, totalSpent: 0 },
  { id: 'Sous', displayId: 91, name: 'Client Soumis', phone: '(438) 884-3566', address: 'Montreal', notes: 'Supplement arrêter condo juin 2025 statut inactif', orders: 0, totalSpent: 0 },
  { id: 'edmu', displayId: 92, name: 'Edmundo', phone: '(514) 546-2017', address: 'Montreal', notes: 'Ex de Philippe Rivard statut inactif', orders: 0, totalSpent: 0 },
  { id: 'Eric2', displayId: 93, name: 'Eric Deveau', phone: '(438) 370-3310', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Ffbd', displayId: 94, name: 'Ffbeaudry', phone: '(514) 727-2437', address: 'Village, Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'fnk', displayId: 95, name: 'FRANK', phone: '', address: 'Montreal', notes: 'Voleur menteur blacklisted', orders: 0, totalSpent: 0 },
  { id: 'gser', displayId: 96, name: 'Gabriel Serrano', phone: '(514) 299-8980', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'Jay', displayId: 97, name: 'Jay Frontenac', phone: '(514) 928-7638', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'medo', displayId: 98, name: 'Meedo Mohamed', phone: '(514) 999-5747', address: 'Pyramides olympiques', notes: 'Blacklisted', orders: 0, totalSpent: 0 },
  { id: 'momo', displayId: 99, name: 'Momo', phone: '(438) 921-9195', address: 'Montreal', notes: 'Ami de meedo blacklisted', orders: 0, totalSpent: 0 },
  { id: 'nicb', displayId: 100, name: 'Nicholas Bougie', phone: '(438) 879-0230', address: 'Montreal', notes: '', orders: 0, totalSpent: 0 },
  { id: 'sean', displayId: 101, name: 'Shean black', phone: '(514) 922-8819', address: 'Montreal', notes: 'Doit 100$', orders: 0, totalSpent: 0 },
  { id: 'simk', displayId: 102, name: 'Simon Kingston', phone: '(514) 791-1785', address: 'Montreal', notes: 'Doit 200$', orders: 0, totalSpent: 0 },
];

export const initialProducts: Product[] = [
  { id: 'p1', name: 'T Premium', type: 'g', stock: 0, price: 0, referenceQuantity: '1g/3.5g/28g', suggestedPrice: '50/160/550', cost: '13/45/350' },
  { id: 'p2', name: 'T', type: 'g', stock: 599, price: 0, referenceQuantity: '1g/3.5g/7g/14g/28g/100g/500g/1000g', suggestedPrice: '30/130/200/300/450/1800/4900/8000', cost: '6/21/42/84/168/600/3000/6000' },
  { id: 'p3', name: 'G', type: 'ml', stock: 2310, price: 0, referenceQuantity: '1ml/100ml/1000ml', suggestedPrice: '2/180/1400', cost: '0.7/70/700' },
  { id: 'p4', name: 'V Blue', type: 'unit', stock: 0, price: 0, referenceQuantity: '100mg', suggestedPrice: '6', cost: '2' },
  { id: 'p5', name: 'V Purple', type: 'unit', stock: 0, price: 0, referenceQuantity: '100mg', suggestedPrice: '8', cost: '2' },
  { id: 'p6', name: 'V Red', type: 'unit', stock: 0, price: 0, referenceQuantity: '150mg', suggestedPrice: '10', cost: '2' },
  { id: 'p7', name: 'V Black', type: 'unit', stock: 238, price: 0, referenceQuantity: '200mg', suggestedPrice: '10', cost: '3' },
  { id: 'p8', name: 'V Levi', type: 'unit', stock: 0, price: 0, referenceQuantity: '60mg', suggestedPrice: '12', cost: '3' },
  { id: 'p9', name: 'V Kam Jelly', type: 'unit', stock: 0, price: 0, referenceQuantity: '100mg', suggestedPrice: '10', cost: '3' },
  { id: 'p10', name: 'Lis 20mg', type: 'unit', stock: 0, price: 0, referenceQuantity: '20mg', suggestedPrice: '8', cost: '3' },
  { id: 'p11', name: 'Lis 60mg', type: 'unit', stock: 0, price: 0, referenceQuantity: '60mg', suggestedPrice: '10', cost: '3' },
  { id: 'p12', name: 'Lis 80mg', type: 'unit', stock: 0, price: 0, referenceQuantity: '80mg', suggestedPrice: '12', cost: '3' },
  { id: 'p13', name: 'S', type: 'unit', stock: 10, price: 0, referenceQuantity: '', suggestedPrice: '3', cost: '1' },
  { id: 'p14', name: 'E', type: 'unit', stock: 485, price: 0, referenceQuantity: '', suggestedPrice: '5', cost: '2' },
  { id: 'p15', name: 'M', type: 'unit', stock: 727, price: 0, referenceQuantity: '', suggestedPrice: '8', cost: '4' },
  { id: 'p16', name: 'M 1g', type: 'g', stock: 20, price: 0, referenceQuantity: '1g', suggestedPrice: '70', cost: '20' },
  { id: 'p17', name: 'W', type: 'g', stock: 196, price: 0, referenceQuantity: '1g/3.5g/28g', suggestedPrice: '5/20/90', cost: '3/11/60' },
  { id: 'p18', name: 'H 1g', type: 'g', stock: 8, price: 0, referenceQuantity: '1g', suggestedPrice: '10', cost: '3' },
  { id: 'p19', name: 'K', type: 'unit', stock: 110, price: 0, referenceQuantity: '1 unit/28 units', suggestedPrice: '90/600', cost: '20/550' },
  { id: 'p20', name: 'C', type: 'g', stock: 16, price: 0, referenceQuantity: '0.5g/1g/28g', suggestedPrice: '50/90/1150', cost: '25/50/950' },
  { id: 'p21', name: 'Shrooms', type: 'g', stock: 1, price: 0, referenceQuantity: '3.5g', suggestedPrice: '25', cost: '17' },
  { id: 'p22', name: 'Pop 30ml', type: 'unit', stock: 0, price: 0, referenceQuantity: '30ml', suggestedPrice: '55', cost: '25' },
  { id: 'p23', name: 'Pop 60ml', type: 'unit', stock: 3, price: 0, referenceQuantity: '60ml', suggestedPrice: '75', cost: '33' },
  { id: 'p24', name: 'Pipe', type: 'unit', stock: 2, price: 10, referenceQuantity: '1 unit', suggestedPrice: '10', cost: '4' },
  { id: 'p25', name: 'Rent', type: 'unit', stock: 0, price: 700, referenceQuantity: '1 unit', suggestedPrice: '700', cost: '0' },
  { id: 'p26', name: 'k (.3g)', type: 'unit', stock: 0, price: 35, referenceQuantity: '1 unit', suggestedPrice: '35', cost: '7' },
];

export const initialOrders: Order[] = [];
export const initialExpenses: Expense[] = [];
export const initialLogs: LogEntry[] = [];
